services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gabi-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NODE_ISLOCAL=true
      - VIDEO_DIR=/app/GABI/Videos
      - THUMB_DIR=/app/GABI/Thumbs
      - TEMP_DIR=/app/Temp
      - AVATAR_DIR=/app/GABI/Avatars
      - DS_SALT=thisIsASecretSaltValue
      - DB_BACKUP_MAIN=/app/backups/main
      - DB_BACKUP_SUB=/app/backups/sub
      - VALID_VIDEO_EXTENSIONS=.mp4,.mkv,.avi,.mov,.wmv,.flv,.webm
      - INVITATION_CODE=youtrInvitationCodeHere
      - FRONTEND_ORIGIN=https://yourdomain.com,https://upload.yourdomain.com,http://localhost:8443
      - BACKEND_USE_HTTPS=true
    volumes:
      - ./backend/db:/app/db
      - ./backend/logs:/app/logs
      - ./backend/Temp:/app/Temp
      - ./backend/Backups:/app/backups/main
      - ./backend/cert:/app/cert:ro
      - /path/to/your/ext/folder:/app/GABI
      - /path/to/your/ext/backup/folder:/app/backups/sub
    restart: always

  frontend:
    build:
      context: ./frontend_react
      dockerfile: Dockerfile
    container_name: gabi-frontend
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    environment:
      - PORT=8080
      - VITE_API_BASE_URL=https://upload.yourdomain.com/api
    volumes:
      - ./frontend_react/cert:/etc/nginx/certs:ro
      # VITE_UPLOAD_API_URL please navigate to frontend_react/src/config.js to set this value
    restart: always
