services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gabi-backend
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NODE_ISLOCAL=true
      - VIDEO_DIR=/app/Videos
      - THUMB_DIR=/app/Thumbs
      - TEMP_DIR=/app/Temp
      - AVATAR_DIR=/app/Avatars
      - DS_SALT=thisIsASecretSaltValue # 建議在部署時透過 .env 更改
      - DB_BACKUP_MAIN=/app/backups/main
      - DB_BACKUP_SUB=/app/backups/sub
    volumes:
      - ./backend/backups/main:/app/backups/main
      - ./backend/backups/sub:/app/backups/sub
    restart: always

  frontend:
    build:
      context: ./frontend_react
      dockerfile: Dockerfile
    container_name: gabi-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
